# Generated by Django 6.0.2 on 2026-03-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. T1, Table 5', max_length=30, unique=True)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved')], db_index=True, default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
